# Biblioteca Numpy

### Arreglos en NumPy

In [1]:
import numpy as np

data = np.random.randn(2, 3)

In [2]:
data

array([[ 0.50333744, -0.27348902,  0.83041049],
       [-0.07259897, -0.23370272, -0.63519323]])

In [11]:
np.linspace(1,4,6)

array([ 1. ,  1.6,  2.2,  2.8,  3.4,  4. ])

In [5]:
print(data)
data * 10,  data + data

[[ 1.09282928 -1.55417616 -0.38250352]
 [ 0.78305907 -1.42667052 -0.89204745]]


(array([[ 10.92829281, -15.54176164,  -3.82503518],
        [  7.83059068, -14.26670519,  -8.92047449]]),
 array([[ 2.18565856, -3.10835233, -0.76500704],
        [ 1.56611814, -2.85334104, -1.7840949 ]]))

Estos arreglos de numpy podemos crearlos a partir de arreglos de python, por ejemplo:


In [6]:
data = [[1,2,3], [4,5,6]]
arr = np.array(data)



Y ahora podemos utilizar operaciones como `shape` o `dim`

In [7]:
print(arr.shape)
print(arr.ndim)

(2, 3)
2


In [8]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

### Indexando arreglos

In [9]:
arr = np.arange(8)

In [10]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [11]:
arr[5] # vemos el elemento en la posición 5 (contando desde el 0)

5

In [12]:
arr[2:5] # desde la pos 2 a la 4.

array([2, 3, 4])

In [13]:
arr[:] = 58 # Si asignamos un valor esto será _broadcasteado_ a todo el rango 

In [14]:
arr

array([58, 58, 58, 58, 58, 58, 58, 58])

### Slicing

In [15]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])



In [16]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr2d[:1]

array([[1, 2, 3]])

In [22]:
arr2d[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr2d[1, :2]

array([4, 5])

In [24]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Filtros booleanos

In [25]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [26]:
arr2d < 2

array([[ True,  True,  True],
       [False,  True,  True],
       [False, False, False]], dtype=bool)

In [27]:
arr2d[arr2d < 2]

array([1, 0, 0, 0, 0])

In [28]:
arr2d > 0

array([[ True, False, False],
       [ True, False, False],
       [ True,  True,  True]], dtype=bool)

In [29]:
arr2d[arr2d > 0]

array([1, 4, 7, 8, 9])

### Funciones universales

In [40]:
arr = np.arange(10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.sqrt(arr)


array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [38]:
np.abs([-2, 1, -3])

array([2, 1, 3])

In [41]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [42]:
np.add(arr, arr)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Funciones de agregación

In [43]:
arr = np.random.randn(5, 4)
arr

array([[ 0.45002698,  0.20361901,  1.52856927, -1.85929436],
       [-1.79947947,  1.28655176, -0.6566373 ,  0.10053272],
       [-0.09605663,  0.69039945,  0.82386572, -0.67768468],
       [ 0.39540581,  0.56635867,  2.19572879, -0.43528137],
       [-0.10018508,  1.47050717,  0.63444815, -0.39736896]])

In [44]:
arr.mean() # o np.mean(arr)

0.2162012826961362

In [45]:
arr.sum()

4.3240256539227238